import { Component } from "./entryComponent.js"

export const entriesDOM = {

  // Takes Array of OBJs
  renderJournalEntries(entries) {

    // Loop over Array, passing each entryObj into a func
    entries.forEach(entry => {

      // Select html output...
      document.querySelector('.entryLog')
        
        // ... append the html component generated by makeJournalEntry
        .appendChild(Component.makeJournalEntry(entry))
    });
  }
} 